### PR TITLE
Allow rc version of webpack

### PR DESCRIPTION
**Pull request by bondz**
An RC version of webpack 2 was published, currently peer dependency warnings are thrown

### CODE REVIEW

**Comment by jscheid** [comment]
@bondz thanks for your PR. I've just run our tests against `2.2.0-rc.0` and unfortunately they fail, so the current dependency version is actually correct :-/

I'll try to take a look at this soon, or would you like to take a stab? It seems to be something simple with `hasRuntime`, I remember we special-cased this before, it's probably a simply change.

If you want to give it a try, would you mind changing `.travis.yml` so that CI runs against the RC as well?

**Comment by jscheid** [comment]
Never mind, I had the wrong version of `extract-text-webpack-plugin`.

**Comment by jscheid** [comment]
@bondz I've relaxed the version requirement a little so that we don't have to publish a new release for every future release candidate.

https://github.com/waysact/webpack-subresource-integrity/blob/5ba9c6c6ebeac50a63fb6a35444128a7984efc1b/package.json#L55

Released in v0.8.2.

**Comment by bondz** [comment]
@jscheid 👍 Glad this is sorted out.

**Pull request merged**
