### PR TITLE
Support multiple common chunks

### PR DESCRIPTION
**Pull request by jscheid**
Closes #58

### CODE REVIEW

**Comment by arthurjamain** [comment]
Hey there !

I've succeeded in getting a successful build and all hashes with your solution. 🎉 

All that's needed for my case to work is a small patch on l. 240 in `index.js`, right after the `recurse` call.

`depChunkIds = depChunkIds.filter((v, i, s) => s.indexOf(v) === i);` This filters out duplicate chunk IDs from the array. From what I gathered, with my configuration, the recuse call `concat`'d the same IDs over and over again, deepening the call stack critically (when I killed the process there were 90k entries in the array, with 10 of them being unique).

^ The explanation feels a bit shaky, but empirically this fixes my issue, and from what I gather it makes sense anyway.

**Comment by arthurjamain** [comment]
This commit fixes all of my problems ! <3

**Comment by jscheid** [comment]
Hey, thanks for testing and all. Sorry was travelling last week and only now getting back to it.

I spent an hour yesterday to try and come up with a test case but no dice.

I suspect what you were seeing is actually not an infinite loop but quadratic or exponential behaviour. Out of curiosity, how many chunks does your project have approximately?

Anyway, I think it's fine to add this last change without a test because without it it's obviously broken. Planning to release this soon.

**Comment by arthurjamain** [comment]
No probs 👍 Thanks for being active !

We have about ~60 chunks, of which ~30 are anonymous and 3 are communchunks output.

**Pull request merged**
